Wait for external container dependencies on deploy
srl-labs/containerlab pull request #1022
Opened 2022-09-12 08:55 UTC by steiler

By querying the runtime I want to figure out if the external containers that denpending containers rely up on are already running and only then start to actually deploy the dependent container.

2022-09-16 14:18 UTC, steiler commented
@YutaroHayakawa Inspired by your comment in #1013 I've added the following functionality.
Please take a look if this helps with your usecase.

If there is an external dependency like as what you described, this will check and delay the deployment of the container that is meant to be started in the other network namespace. If the "network-mode:container<ExternalContainerName>" referenced  container is found and in state running, the deployment of the node is continued.

2022-09-16 14:40 UTC, steiler commented
**Sample Topo:**
```
name: srl01

topology:
  kinds:
    srl:
      type: ixrd3
      image: ghcr.io/nokia/srlinux
    linux:
      image: ghcr.io/hellt/network-multitool
  nodes:
    srl1:
      kind: srl
    srl2:
      kind: srl
    srl3:
      kind: srl
      network-mode: container:nginx
    linux:
      kind: linux
```
**Log Snippet:**
```
INFO[0308] container "srl3" depends on external container "nginx", which is not running yet. waited 30 seconds. will continue to wait 
INFO[0309] container "srl3" depends on external container "nginx", which is not running yet. waited 31 seconds. will continue to wait 
INFO[0310] container "srl3" depends on external container "nginx", which is not running yet. waited 32 seconds. will continue to wait 
INFO[0311] container "srl3" depends on external container "nginx", which is not running yet. waited 33 seconds. will continue to wait 
INFO[0312] container "srl3" depends on external container "nginx", which is not running yet. waited 34 seconds. will continue to wait 
INFO[0313] container "srl3" depends on external container "nginx", which is not running yet. waited 35 seconds. will continue to wait 
INFO[0314] container "srl3" depends on external container "nginx", which is not running yet. waited 36 seconds. will continue to wait 
INFO[0315] container "srl3" starts since external container "nginx" is running now 
DEBU[0315] creating links...                            
DEBU[0315] Worker 3 terminating...                      
```

**External Command:**
```
docker run --rm -it --name nginx ubuntu bash
```
Starting a container with the name `nginx`
Issued after INFO[314]

2022-09-21 16:05 UTC, hellt requested changes

2022-09-21 19:43 UTC, steiler commented on clab/clab.go
> +		counter++
interesting, did not know about this ticker concept. Thanks.
Implemented it!

2022-09-21 19:45 UTC, steiler commented on clab/clab.go
> +			log.Errorf("container %q waited %d seconds for external dependency container %q to come up, which did not happen. Giving up now", nodename, waitTimeout*waitTimeoutCounter, contName)
same as above

2022-09-21 19:46 UTC, steiler commented on clab/clab.go
> +		log.Infof("container %q depends on external container %q, which is not running yet. waited %d seconds. continue to wait", nodename, contName, waitTimeout*counter)
same as above

2022-09-22 08:22 UTC, hellt commented on clab/clab.go
> +				log.Infof("container %q starts since external container %q is running now", nodename, contName)
yes, it is only for nodes defined in clab that we should use a `node` term. The external references are containers

2022-09-22 09:08 UTC, steiler commented on clab/clab.go
> +				log.Infof("container %q starts since external container %q is running now", nodename, contName)
done!

2022-09-22 09:57 UTC, hellt approved these changes

2022-09-22 10:01 UTC, merged