k8s_kind: Display kind provisioning log
srl-labs/containerlab pull request #1894
Opened 2024-02-18 08:36 UTC by YutaroHayakawa

Currently, kind provisioning is not logged, so we cannot know how provisioning is going on. Implement a logger.

2024-02-18 08:45 UTC, hellt commented
thanks @YutaroHayakawa 

@steiler I thought of the same when I did local testing. Seems like seeing the cluster provisioning log (which is not verbose anyhow) is what you would want to have given this becomes an important node of the lab

2024-02-18 11:58 UTC, YutaroHayakawa commented
Hmm, tests are failing, but they seem not related to this PR. It seems like the `exec` is failing.

```
time="2024-02-18T08:48:10Z" level=error msg="Failed to execute command \"ip a del dev eth1\" on the node \"k02-control-plane\". rc=1,\nstdout:\n\nstderr:\nCannot find device \"eth1\"\n"
time="2024-02-18T08:48:10Z" level=error msg="Failed to execute command \"ip a add dev eth1 192.168.237.3/24\" on the node \"k02-control-plane\". rc=1,\nstdout:\n\nstderr:\nCannot find device \"eth1\"\n"
time="2024-02-18T08:48:10Z" level=error msg="Failed to execute command \"ip a add dev eth1 192.168.237.20/24\" on the node \"alpine\". rc=1,\nstdout:\n\nstderr:\nip: can't find device 'eth1'\n"
time="2024-02-18T08:48:10Z" level=error msg="Failed to execute command \"ip a del dev eth1\" on the node \"k01-control-plane\". rc=2,\nstdout:\n\nstderr:\nRTNETLINK answers: Operation not supported\n"
time="2024-02-18T08:48:10Z" level=info msg="Executed command \"ip a add dev eth1 192.168.237.1/24\" on the node \"k01-control-plane\". stdout:\n"
time="2024-02-18T08:48:10Z" level=error msg="Failed to execute command \"ip a del dev eth1\" on the node \"k01-worker\". rc=2,\nstdout:\n\nstderr:\nRTNETLINK answers: Operation not supported\n"
time="2024-02-18T08:48:10Z" level=info msg="Executed command \"ip a add dev eth1 192.168.237.2/24\" on the node \"k01-worker\". stdout:\n"
time="2024-02-18T08:48:10Z" level=warning msg="Cannot parse export template /etc/containerlab/templates/export/auto.tmpl: open /etc/containerlab/templates/export/auto.tmpl: no such file or directory"
```

From what I can see from logs, `eth1` is attached to the node at the time of checking, but assigning address with `exec` is failing somehow.

2024-02-20 07:36 UTC, steiler commented
@YutaroHayakawa Cool you're already using this feature. And thanks for the PR.
To me it is looking good. But I think id would be good to have Line 191 - 250 in a seperate file.
https://github.com/srl-labs/containerlab/pull/1894/files#diff-6fae1f127318ac4b24937dba62935590c5ab3c9a3f9504e8c7d74e1b0ff7bd5bR191-R250 
So if you can move that we can merge I think!

2024-02-20 07:38 UTC, steiler requested changes
@YutaroHayakawa Cool you're already using this feature. And thanks for the PR.
To me it is looking good. But I think id would be good to have Line 191 - 250 in a seperate file.
https://github.com/srl-labs/containerlab/pull/1894/files#diff-6fae1f127318ac4b24937dba62935590c5ab3c9a3f9504e8c7d74e1b0ff7bd5bR191-R250
So if you can move that we can merge I think!

2024-02-21 03:35 UTC, YutaroHayakawa commented
Thanks @steiler for your review. Fixed.

2024-02-21 08:32 UTC, steiler approved these changes
Thanks @YutaroHayakawa
lgtm

2024-02-21 08:36 UTC, merged